"""add colunm certificate

Revision ID: 071bc48d7d98
Revises: 644b12ab8c4e
Create Date: 2026-06-09 23:40:21.803832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071bc48d7d98'
down_revision: Union[str, Sequence[str], None] = '644b12ab8c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('CompanyCertificate', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'CompanyCertificate')
    # ### end Alembic commands ###
