"""change table company

Revision ID: 18826e9b5c4c
Revises: 6b5252eb4c86
Create Date: 2026-06-10 01:41:16.237111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18826e9b5c4c'
down_revision: Union[str, Sequence[str], None] = '6b5252eb4c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'CompanyIsActive')
    op.drop_column('company', 'CompanyIsVerified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('CompanyIsVerified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('company', sa.Column('CompanyIsActive', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
