"""change relactionship table

Revision ID: 22ab86f5e696
Revises: 87a590218965
Create Date: 2026-06-10 03:48:22.155008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22ab86f5e696'
down_revision: Union[str, Sequence[str], None] = '87a590218965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('company', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'company', ['user_id'])
    op.alter_column('event_codes', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'event_codes', ['user_id'])
    op.drop_constraint(op.f('event_codes_company_id_fkey'), 'event_codes', type_='foreignkey')
    op.drop_column('event_codes', 'company_id')
    op.alter_column('event_token', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'event_token', ['user_id'])
    op.drop_constraint(op.f('event_token_company_id_fkey'), 'event_token', type_='foreignkey')
    op.drop_column('event_token', 'company_id')
    op.add_column('users', sa.Column('role_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('user', 'admin', 'owner', 'company', name='role_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('event_token', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('event_token_company_id_fkey'), 'event_token', 'company', ['company_id'], ['id'])
    op.drop_constraint(None, 'event_token', type_='unique')
    op.alter_column('event_token', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('event_codes', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('event_codes_company_id_fkey'), 'event_codes', 'company', ['company_id'], ['id'])
    op.drop_constraint(None, 'event_codes', type_='unique')
    op.alter_column('event_codes', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'company', type_='unique')
    op.alter_column('company', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('roles')
    # ### end Alembic commands ###
