"""Change table

Revision ID: 60387b2b04a0
Revises: 071bc48d7d98
Create Date: 2026-06-10 00:46:40.315583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60387b2b04a0'
down_revision: Union[str, Sequence[str], None] = '071bc48d7d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'company', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'user_id')
    # ### end Alembic commands ###
