"""fixEventToken

Revision ID: 644b12ab8c4e
Revises: a6e54917a418
Create Date: 2026-06-09 21:30:28.945832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644b12ab8c4e'
down_revision: Union[str, Sequence[str], None] = 'a6e54917a418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_token', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('event_token', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_token', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('event_token', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
