"""change table

Revision ID: 6b5252eb4c86
Revises: 60387b2b04a0
Create Date: 2026-06-10 01:38:58.018091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5252eb4c86'
down_revision: Union[str, Sequence[str], None] = '60387b2b04a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'passwordCompanyHashed')
    op.drop_column('company', 'emailCompany')
    op.drop_column('company', 'tellCompany')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('tellCompany', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('company', sa.Column('emailCompany', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('company', sa.Column('passwordCompanyHashed', sa.VARCHAR(length=75), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
