"""new table

Revision ID: 76155f2d661c
Revises: 
Create Date: 2026-06-09 01:47:07.343326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76155f2d661c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nameCompany', sa.String(length=50), nullable=False),
    sa.Column('emailCompany', sa.String(length=50), nullable=False),
    sa.Column('passwordCompanyHashed', sa.String(length=75), nullable=False),
    sa.Column('tellCompany', sa.String(length=50), nullable=False),
    sa.Column('addressCompany', sa.String(length=100), nullable=False),
    sa.Column('CompanyNIT', sa.String(length=50), nullable=False),
    sa.Column('CompanyNITDV', sa.String(length=1), nullable=False),
    sa.Column('CompanyLogo', sa.String(length=255), nullable=True),
    sa.Column('CompanyBanner', sa.String(length=255), nullable=True),
    sa.Column('CompanyIsActive', sa.Boolean(), nullable=False),
    sa.Column('CompanyIsVerified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fullName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=75), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'owner', name='role_enum'), nullable=False),
    sa.Column('tell', sa.String(length=50), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('type', sa.Enum('resetPassword', 'verifyEmail', name='type_code_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.Enum('access', 'refresh', name='tokentype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_token')
    op.drop_table('event_codes')
    op.drop_table('users')
    op.drop_table('company')
    # ### end Alembic commands ###
