"""make company_id nullable

Revision ID: a6e54917a418
Revises: 76155f2d661c
Create Date: 2026-06-09 20:52:19.377383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e54917a418'
down_revision: Union[str, Sequence[str], None] = '76155f2d661c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_codes', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('event_codes', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_codes', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('event_codes', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
